// GENERATED by scripts/gen-registry.ts — do not edit.
export const UI_RECIPES = [
  {
    name: 'ascii-hero',
    type: 'ui',
    description:
      'Decorative hero-section character field — a monospaced grid of glyphs drifting, pulsing, or wiping in on a managed canvas, built on useCharacterField.',
    command: 'aihu add ascii-hero',
    dependencies: [],
    registryDependencies: [],
    variants: {
      mode: ['drift', 'pulse', 'reveal'],
    },
  },
  {
    name: 'aurora',
    type: 'ui',
    description:
      'Decorative animated aurora-borealis-style background wash — pure CSS layered gradients, blur, and mix-blend-mode, no canvas.',
    command: 'aihu add aurora',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'badge',
    type: 'ui',
    description: 'Presentational badge recipe — inline-flex pill with a variant matrix.',
    command: 'aihu add badge',
    dependencies: [],
    registryDependencies: [],
    variants: {
      variant: ['default', 'secondary', 'destructive', 'outline'],
    },
  },
  {
    name: 'before-after',
    type: 'ui',
    description:
      'Drag-to-reveal image comparison, built on the AihuSliderRoot primitive — keyboard-operable divider between named before/after slots.',
    command: 'aihu add before-after',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'big-back',
    type: 'ui',
    description:
      'Presentational oversized watermark-style text, typically a footer wordmark. Decorative, hidden from the accessibility tree.',
    command: 'aihu add big-back',
    dependencies: [],
    registryDependencies: [],
    variants: {
      weight: ['bold', 'black'],
    },
  },
  {
    name: 'button',
    type: 'ui',
    description: 'Styled button recipe wrapping a native <button> (variants + sizes).',
    command: 'aihu add button',
    dependencies: [],
    registryDependencies: [],
    variants: {
      variant: ['default', 'destructive', 'outline', 'ghost', 'link'],
      size: ['sm', 'md', 'lg', 'icon'],
    },
  },
  {
    name: 'card',
    type: 'ui',
    description: 'Presentational card recipe with slotted header, body, and footer regions.',
    command: 'aihu add card',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'chat-bubble',
    type: 'ui',
    description:
      'Presentational single chat message bubble — speaker-aware alignment and accent, optional initials avatar.',
    command: 'aihu add chat-bubble',
    dependencies: [],
    registryDependencies: [],
    variants: {
      speaker: ['user', 'assistant'],
    },
  },
  {
    name: 'chat-fab',
    type: 'ui',
    description:
      'Floating action button + non-modal popover panel shell — a generic chat-launcher, deliberately with no chat logic (panel content is a plain slot).',
    command: 'aihu add chat-fab',
    dependencies: ['@aihu/primitives'],
    registryDependencies: ['popover'],
    variants: {
      corner: ['bottom-right', 'bottom-left', 'top-right', 'top-left'],
    },
  },
  {
    name: 'checkbox',
    type: 'ui',
    description:
      'Styled checkbox recipe — light-DOM element extending the headless AihuCheckboxRoot primitive (tri-state, Space toggle, native form participation).',
    command: 'aihu add checkbox',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'community-badge',
    type: 'ui',
    description:
      'Presentational social-proof pill — pairs a status-dot-style lead slot with a metric.',
    command: 'aihu add community-badge',
    dependencies: [],
    registryDependencies: ['status-dot'],
    variants: {
      tone: ['neutral', 'accent'],
    },
  },
  {
    name: 'dialog',
    type: 'ui',
    description:
      'Styled modal dialog recipe — light-DOM pieces extending the headless AihuDialog primitives (focus-trap + return-focus, Escape-to-close, aria-modal, click-outside dismissal).',
    command: 'aihu add dialog',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'eyebrow-pill',
    type: 'ui',
    description:
      'Presentational label pill, typically preceding a heading. Composes with status-dot in its lead slot.',
    command: 'aihu add eyebrow-pill',
    dependencies: [],
    registryDependencies: ['status-dot'],
    variants: {
      tone: ['neutral', 'accent', 'success', 'warning'],
    },
  },
  {
    name: 'floating-sparkles',
    type: 'ui',
    description:
      'Decorative ambient particle field — small glowing dots drifting and twinkling on a managed canvas, built on useParticleField.',
    command: 'aihu add floating-sparkles',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'glass-card',
    type: 'ui',
    description:
      'Presentational frosted-glass surface card — backdrop-filter blur over a translucent, color-mixed background.',
    command: 'aihu add glass-card',
    dependencies: [],
    registryDependencies: [],
    variants: {
      padding: ['sm', 'md', 'lg'],
    },
  },
  {
    name: 'goldeneye',
    type: 'ui',
    description:
      'Decorative watchful eye — a glowing iris with a pupil that autonomously sweeps a slow Lissajous scan, built directly on useCanvasSurface.',
    command: 'aihu add goldeneye',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'gradient-text',
    type: 'ui',
    description: "Presentational text decoration — applies the pack's brand gradient as text fill.",
    command: 'aihu add gradient-text',
    dependencies: [],
    registryDependencies: [],
    variants: {
      weight: ['normal', 'medium', 'semibold', 'bold'],
      font: ['sans', 'serif'],
    },
  },
  {
    name: 'input',
    type: 'ui',
    description:
      'Presentational input recipe — light-DOM custom element wrapping a native <input> that joins the outer form, with token-driven styling.',
    command: 'aihu add input',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'label',
    type: 'ui',
    description:
      'Presentational label recipe — light-DOM custom element wrapping a native <label> with a forwarded `for` association and token-driven styling.',
    command: 'aihu add label',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'logo-marquee',
    type: 'ui',
    description:
      'Infinite horizontal auto-scrolling row of logos — CSS-only, pauses on hover/focus and honors reduced motion.',
    command: 'aihu add logo-marquee',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'logo-row',
    type: 'ui',
    description:
      'Presentational flex row for partner/press logos — muted+grayscale at rest, full color on hover.',
    command: 'aihu add logo-row',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'mock-ide',
    type: 'ui',
    description:
      'Decorative fake code-editor window chrome — traffic-light dots + title bar over a slotted code body.',
    command: 'aihu add mock-ide',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'node-graph-background',
    type: 'ui',
    description:
      'Decorative animated network background — drifting nodes joined by distance-faded connecting lines on a managed canvas, built on useCanvasSurface.',
    command: 'aihu add node-graph-background',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'popover',
    type: 'ui',
    description:
      'Styled non-modal popover recipe — light-DOM pieces extending the headless AihuPopover primitives (disclosure trigger, positioned panel, outside-pointerdown + Escape dismissal, no focus trap).',
    command: 'aihu add popover',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'pricing-card',
    type: 'ui',
    description:
      "Pricing tier card — tier/price/period, an optional featured accent border/elevation, and a default slot for the consumer's feature list.",
    command: 'aihu add pricing-card',
    dependencies: [],
    registryDependencies: [],
    variants: {
      featured: ['off', 'on'],
    },
  },
  {
    name: 'prompt',
    type: 'ui',
    description:
      'Presentational single-line AI-prompt-bar look — a rounded pill with a leading icon slot and a placeholder text span; not a real form input.',
    command: 'aihu add prompt',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'prompt-hero',
    type: 'ui',
    description:
      'Larger hero variant composing gradient-text (heading) above a prompt bar, centered layout.',
    command: 'aihu add prompt-hero',
    dependencies: [],
    registryDependencies: ['gradient-text', 'prompt'],
    variants: {},
  },
  {
    name: 'quest-text',
    type: 'ui',
    description:
      'Presentational inline text emphasis for prompts/callouts — underline accent with an optional blinking caret.',
    command: 'aihu add quest-text',
    dependencies: [],
    registryDependencies: [],
    variants: {
      tone: ['neutral', 'accent'],
      caret: ['off', 'on'],
    },
  },
  {
    name: 'rotator',
    type: 'ui',
    description:
      'Presentational rotating headline word/phrase — cycles through a comma-separated item list on a fixed interval, cross-fading each change.',
    command: 'aihu add rotator',
    dependencies: [],
    registryDependencies: [],
    variants: {
      tone: ['neutral', 'accent'],
    },
  },
  {
    name: 'separator',
    type: 'ui',
    description:
      'Presentational separator recipe — token-colored 1px rule with role=separator + aria-orientation.',
    command: 'aihu add separator',
    dependencies: [],
    registryDependencies: [],
    variants: {
      orientation: ['horizontal', 'vertical'],
    },
  },
  {
    name: 'slippy-words',
    type: 'ui',
    description:
      'Presentational sentence where one word wiggles for attention at a time, the highlight advancing left to right, looping.',
    command: 'aihu add slippy-words',
    dependencies: [],
    registryDependencies: [],
    variants: {
      tone: ['neutral', 'accent'],
    },
  },
  {
    name: 'sparkle',
    type: 'ui',
    description:
      'Presentational decorative accent mark — a four-pointed star with an optional shimmer.',
    command: 'aihu add sparkle',
    dependencies: [],
    registryDependencies: [],
    variants: {
      size: ['sm', 'md', 'lg'],
      tone: ['neutral', 'accent'],
      shimmer: ['off', 'on'],
    },
  },
  {
    name: 'stat-counter',
    type: 'ui',
    description:
      'Presentational number that counts up to a target the first time it scrolls into view.',
    command: 'aihu add stat-counter',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'status-dot',
    type: 'ui',
    description:
      'Presentational status indicator — a semantic-colored dot with an optional pulsing liveness ring.',
    command: 'aihu add status-dot',
    dependencies: [],
    registryDependencies: [],
    variants: {
      status: ['neutral', 'online', 'busy', 'away', 'info', 'offline'],
      size: ['sm', 'md', 'lg'],
      pulse: ['off', 'on'],
    },
  },
  {
    name: 'sticky-banner',
    type: 'ui',
    description: 'Presentational full-width announcement bar. No dismiss affordance in this slice.',
    command: 'aihu add sticky-banner',
    dependencies: [],
    registryDependencies: [],
    variants: {
      tone: ['neutral', 'accent', 'warning'],
    },
  },
  {
    name: 'switch',
    type: 'ui',
    description:
      'Styled switch recipe — light-DOM element extending the headless AihuSwitchRoot primitive (binary toggle, Space/Enter activation, native form participation).',
    command: 'aihu add switch',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'temperature',
    type: 'ui',
    description:
      'Styled 3-value response-temperature preset picker (Precise / Balanced / Creative) — light-DOM element extending the headless AihuRadioGroupRoot primitive (roving tabindex, arrow-key selection, native form participation).',
    command: 'aihu add temperature',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'textarea',
    type: 'ui',
    description:
      'Presentational textarea recipe — light-DOM custom element wrapping a native <textarea> that joins the outer form, with token-driven styling.',
    command: 'aihu add textarea',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'token-stream',
    type: 'ui',
    description:
      'Presentational LLM-response-streaming look — reveals a sentence word by word with a blinking caret.',
    command: 'aihu add token-stream',
    dependencies: [],
    registryDependencies: [],
    variants: {
      loop: ['off', 'on'],
    },
  },
  {
    name: 'tooltip',
    type: 'ui',
    description:
      'Styled tooltip recipe — light-DOM pieces extending the headless AihuTooltip primitives (hover/focus open, Escape dismiss, aria-describedby, placement positioning). Non-focus-trapping overlay.',
    command: 'aihu add tooltip',
    dependencies: ['@aihu/primitives'],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'waitlist-form',
    type: 'ui',
    description:
      'Email-capture form with an inline success state — dispatches `waitlist-submit` ({ email }) for the consumer to wire the real request; no popover, no network logic.',
    command: 'aihu add waitlist-form',
    dependencies: [],
    registryDependencies: [],
    variants: {},
  },
  {
    name: 'wibbling-spinner',
    type: 'ui',
    description:
      'Presentational braille-glyph loading spinner — cycles through a fixed frame set on a short interval.',
    command: 'aihu add wibbling-spinner',
    dependencies: [],
    registryDependencies: [],
    variants: {
      size: ['sm', 'md', 'lg'],
      tone: ['neutral', 'accent'],
    },
  },
  {
    name: 'word-roll',
    type: 'ui',
    description:
      'Presentational rolling headline word — cycles through a comma-separated item list, rolling each new word down into a clipped window.',
    command: 'aihu add word-roll',
    dependencies: [],
    registryDependencies: [],
    variants: {
      tone: ['neutral', 'accent'],
    },
  },
] as const

export const EXTENSIONS = [
  {
    name: '@aihu-plugin/agent-readiness',
    version: '2.3.0',
    description: 'Discovery + readiness manifest emitter so agents can introspect aihu apps.',
    kind: 'plugin',
    provides: ['agent-readiness'],
    installation: 'opt-in',
    command: 'bun add @aihu-plugin/agent-readiness',
    npm: 'https://www.npmjs.com/package/@aihu-plugin/agent-readiness',
  },
  {
    name: '@aihu-plugin/data',
    version: '2.0.5',
    description: 'Reactive data loaders and resource primitives for aihu.',
    kind: 'plugin',
    provides: ['data'],
    installation: 'opt-in',
    command: 'bun add @aihu-plugin/data',
    npm: 'https://www.npmjs.com/package/@aihu-plugin/data',
  },
  {
    name: '@aihu-plugin/drizzle',
    version: '0.1.6',
    description:
      'Drizzle ORM data adapter for aihu — typed createResource fetchers and defineLoader helpers (Postgres / SQLite / libSQL).',
    kind: 'plugin',
    provides: ['database'],
    installation: 'opt-in',
    command: 'bun add @aihu-plugin/drizzle',
    npm: 'https://www.npmjs.com/package/@aihu-plugin/drizzle',
  },
  {
    name: '@aihu-plugin/kindly-note',
    version: '0.2.4',
    description:
      'Runtime syntax highlighting + markdown rendering for aihu — <aihu-code>/<aihu-markdown> custom elements + signal-aware highlight()/renderMarkdown() helpers, powered by published @kindly-note/* packages with lazy loading.',
    kind: 'plugin',
    provides: ['notes'],
    installation: 'opt-in',
    command: 'bun add @aihu-plugin/kindly-note',
    npm: 'https://www.npmjs.com/package/@aihu-plugin/kindly-note',
  },
  {
    name: '@aihu/css-engine',
    version: '0.6.1',
    description: 'aihu CSS engine — Tailwind v4 hard fork with WC-native scoped output.',
    kind: 'provider',
    provides: ['styling'],
    installation: 'opt-in',
    command: 'bun add @aihu/css-engine',
    npm: 'https://www.npmjs.com/package/@aihu/css-engine',
  },
  {
    name: '@aihu/plugin',
    version: '0.1.0',
    description:
      'Plugin substrate shared by @aihu/server and the meta-framework — runtime hook surface.',
    kind: 'plugin',
    provides: ['extension-authoring'],
    installation: 'opt-in',
    command: 'bun add @aihu/plugin',
    npm: 'https://www.npmjs.com/package/@aihu/plugin',
  },
  {
    name: '@aihu/plugin-demo',
    version: '0.1.4',
    description:
      'Canonical proof-of-life for the @aihu/plugin API — exercises macros, middleware, and transforms.',
    kind: 'plugin',
    provides: ['example'],
    installation: 'opt-in',
    command: 'bun add @aihu/plugin-demo',
    npm: 'https://www.npmjs.com/package/@aihu/plugin-demo',
  },
  {
    name: '@aihu/router',
    version: '0.5.0',
    description: 'File-based router for the aihu meta-framework.',
    kind: 'provider',
    provides: ['routing'],
    installation: 'opt-in',
    command: 'bun add @aihu/router',
    npm: 'https://www.npmjs.com/package/@aihu/router',
  },
] as const
