#!/usr/bin/env bun
/**
 * Build the human and machine registry surfaces from package source.
 *
 * - `src/data/registry.ts` feeds the prerendered /registry page.
 * - `public/registry/index.json` is the hosted v1 catalog. Recipe sources are
 *   inlined so future CLI clients do not need an npm install before copying a
 *   component into a project.
 *
 * Both outputs are deterministic and committed. Run with `--check` in CI to
 * detect drift without rewriting files.
 */
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, extname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

interface RegistryFile {
  path: string
  source?: string
  type: 'component' | 'style' | 'lib' | 'block'
}

interface RegistryItem {
  name: string
  type: string
  description?: string
  files: RegistryFile[]
  dependencies?: string[]
  registryDependencies?: string[]
  variants?: Record<string, string[]>
  meta?: Record<string, unknown>
}

interface Registry {
  items: RegistryItem[]
}

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, '../../..')
const UI_ROOT = join(REPO, 'packages/ui')
const DOCS_ROOT = join(REPO, 'apps/docs')
const REPOSITORY = 'https://github.com/aihu-project/aihu'

const EXTENSION_SPECS = [
  { dir: 'router', kind: 'provider', provides: ['routing'] },
  { dir: 'css-engine', kind: 'provider', provides: ['styling'] },
  { dir: 'plugin', kind: 'plugin', provides: ['extension-authoring'] },
  { dir: 'plugin-agent-readiness', kind: 'plugin', provides: ['agent-readiness'] },
  { dir: 'plugin-data', kind: 'plugin', provides: ['data'] },
  { dir: 'plugin-demo', kind: 'plugin', provides: ['example'] },
  { dir: 'plugin-drizzle', kind: 'plugin', provides: ['database'] },
  { dir: 'plugin-kindly-note', kind: 'plugin', provides: ['notes'] },
] as const

const registry = JSON.parse(readFileSync(join(UI_ROOT, 'registry.json'), 'utf8')) as Registry

const components = registry.items.map((item) => ({
  name: item.name,
  type: item.type,
  description: item.description ?? '',
  command: `aihu add ${item.name}`,
  dependencies: item.dependencies ?? [],
  registryDependencies: item.registryDependencies ?? [],
  variants: item.variants ?? {},
}))

const extensions = EXTENSION_SPECS.map(({ dir, kind, provides }) => {
  const manifest = JSON.parse(
    readFileSync(join(REPO, 'packages', dir, 'package.json'), 'utf8'),
  ) as {
    name: string
    version: string
    description?: string
  }
  return {
    name: manifest.name,
    version: manifest.version,
    description: manifest.description ?? '',
    kind,
    provides,
    installation: 'opt-in' as const,
    command: `bun add ${manifest.name}`,
    npm: `https://www.npmjs.com/package/${manifest.name}`,
  }
}).sort((a, b) => a.name.localeCompare(b.name))

const hosted = {
  $schema: 'https://aihu.dev/registry/schema-v1.json',
  schemaVersion: 1,
  name: 'aihu',
  stability: 'experimental',
  contributions: 'closed',
  homepage: 'https://aihu.dev/registry',
  repository: REPOSITORY,
  items: registry.items.map((item) => ({
    ...item,
    files: item.files.map((file) => ({
      ...file,
      source: readFileSync(join(UI_ROOT, file.path), 'utf8'),
    })),
  })),
  extensions,
}

const dataModule =
  `// GENERATED by scripts/gen-registry.ts — do not edit.\n` +
  `export const UI_RECIPES = ${JSON.stringify(components, null, 2)} as const\n\n` +
  `export const EXTENSIONS = ${JSON.stringify(extensions, null, 2)} as const\n`
const hostedJson = `${JSON.stringify(hosted, null, 2)}\n`

function format(path: string, contents: string): string {
  const temporary = `/tmp/aihu-registry-${process.pid}${extname(path)}`
  writeFileSync(temporary, contents)
  const result = Bun.spawnSync([
    join(REPO, 'node_modules/.bin/biome'),
    'format',
    '--write',
    temporary,
  ])
  try {
    if (result.exitCode !== 0) {
      throw new Error(`Biome could not format ${path}: ${result.stderr.toString()}`)
    }
    return readFileSync(temporary, 'utf8')
  } finally {
    unlinkSync(temporary)
  }
}

function emit(path: string, contents: string, check: boolean): void {
  contents = format(path, contents)
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== contents) {
      throw new Error(`${path} is stale; run bun run gen:registry`)
    }
    return
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, contents)
}

const check = process.argv.includes('--check')
emit(join(DOCS_ROOT, 'src/data/registry.ts'), dataModule, check)
emit(join(DOCS_ROOT, 'public/registry/index.json'), hostedJson, check)
console.log(check ? 'registry outputs are current' : 'wrote registry page data and hosted catalog')
